[package]
name = "zombo"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.0"
serde = { version = "1.0.210", features = ["derive"] }

[dev-dependencies]
uuid = {version = "1.10.0", features = ["v4", "fast-rng"]}
